/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _CALC_H_RPCGEN
#define _CALC_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct values {
	int num1;
	int num2;
};
typedef struct values values;

#define CALC 0x31111111
#define CALC_VERS 3

#if defined(__STDC__) || defined(__cplusplus)
#define ADD 1
extern  int * add_3(values *, CLIENT *);
extern  int * add_3_svc(values *, struct svc_req *);
#define SUB 2
extern  int * sub_3(values *, CLIENT *);
extern  int * sub_3_svc(values *, struct svc_req *);
extern int calc_3_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define ADD 1
extern  int * add_3();
extern  int * add_3_svc();
#define SUB 2
extern  int * sub_3();
extern  int * sub_3_svc();
extern int calc_3_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_values (XDR *, values*);

#else /* K&R C */
extern bool_t xdr_values ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_CALC_H_RPCGEN */
