/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "calc.h"
#include <rpc/rpc.h>

int *
add_3_svc(values *argp, struct svc_req *rqstp)
{
	static int  result;
	
	result = argp->num1 + argp->num2;

	return (&result);
}

int *
sub_3_svc(values *argp, struct svc_req *rqstp)
{
	static int  result;

	result = argp->num1 - argp->num2;	
	
	return (&result);
}
