/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */
#include <time.h>
#include <rpc/rpc.h>
#include "date.h"

long *
bin_date_1_svc(void *argp, struct svc_req *rqstp)
{
	static long  timeval;
	
	timeval = time((long*)0);
	
	return &timeval;
}

char **
str_date_1_svc(long *argp, struct svc_req *rqstp)
{
	static char* ptr;
	
	ptr = ctime(argp);
	
	return &ptr;
}
